# Generated by Django 4.1.2 on 2022-12-17 16:04

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(name="note", options={"ordering": ["due_date"]},),
        migrations.AlterField(
            model_name="note",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="due_date",
            field=models.DateTimeField(default=todo.models.one_week_hence),
        ),
    ]
