# Generated by Django 4.1.2 on 2022-12-20 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_note_options_alter_note_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="type",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
